import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {gmwwMembersLiveScript} from '../src/gmww-members-live.js';
import {patchPrivatePlayerCards} from '../src/gmww-player-private-card-patch.js';

const player=patchPrivatePlayerCards(gmwwMembersLiveScript);
test('Offline-first player has two selectable fanned card backs and NO shuffle button or target actions',()=>{
 assert.doesNotThrow(()=>new vm.Script(player));
 assert.match(player,/function gmwwDeckBringToFront\(kind\)/);
 assert.match(player,/gmwwPendingPrivateCardTap='';gmwwDeckBringToFront\(kind\);openPrivateCardViewer\(kind\)/);
 assert.doesNotMatch(player,/gmwwShufflePrivateDeck|XÁO BÀI|data-shuffle-deck|gmww-deck-shuffle/);
 assert.match(player,/#gmwwPlayerPrivateDock:not\(\.is-solo\) button\[data-private-card="role"\]/);
 assert.match(player,/#gmwwPlayerPrivateDock:not\(\.is-solo\) button\[data-private-card="artifact"\]/);
 assert.match(player,/#gmwwPlayerPrivateDock:not\(\.is-solo\)\[data-deck-top="artifact"\]/);
 assert.match(player,/#game #gmwwArtifactBar,#game \.gmww-artifact-bar/);
 assert.match(player,/display:none!important/);
 assert.match(player,/function closePrivateCardViewer\(\)\{\s*if\(\$\('#game'\)\?\.dataset\.privateCardView==='open'/);
 assert.match(player,/gmwwViewedRoleDeck\.add\(gmwwDeckRoleIdentity\(\)\);gmwwDeckPreferredTop='artifact'/);
 assert.match(player,/gmwwDeckPreferredTop=gmwwDeckRoleWasViewed\(\)\?'artifact':'role'/);
 assert.match(player,/dock\.dataset\.deckTop=state\.artifact&&gmwwDeckPreferredTop==='artifact'\?'artifact':'role'/);
 assert.doesNotMatch(player,/\/api\/rooms\/'\+state\.roomCode\+'\/assignments'/);
});
test('Tapping rear role or artifact switches visual priority without altering assigned data',()=>{
 const start=player.indexOf('const gmwwViewedRoleDeck=new Set();');
 const end=player.indexOf('function renderPlayerPrivateDock(){',start);
 assert.ok(start>0&&end>start);
 const state={roomCode:'AABBCC',participantId:'member:safari',room:{matchId:'match1'},role:{assignmentIndex:0,roleId:'witch',viewedAt:null},artifact:{artifactId:'mirror'}};
 let redraws=0;
 const ctx={state,Set,privateCardAllowed:()=>true,renderPlayerPrivateDock:()=>{redraws++}};
 vm.runInNewContext(player.slice(start,end)+";this.isSeen=gmwwDeckRoleWasViewed;this.raise=gmwwDeckBringToFront;this.markSeen=()=>gmwwViewedRoleDeck.add(gmwwDeckRoleIdentity());this.getTop=()=>gmwwDeckPreferredTop;",ctx);
 assert.equal(ctx.isSeen(),false);
 assert.equal(ctx.getTop(),'role');
 ctx.raise('artifact');assert.equal(ctx.getTop(),'artifact');
 ctx.raise('role');assert.equal(ctx.getTop(),'role');
 assert.equal(redraws,2);
 assert.equal(state.role.roleId,'witch');
 assert.equal(state.artifact.artifactId,'mirror');
 ctx.markSeen();assert.equal(ctx.isSeen(),true);
 state.role={...state.role,roleId:'new-role',viewedAt:null};
 assert.equal(ctx.isSeen(),false,'new assignment should not inherit viewed status');
 state.role.viewedAt='2026-10-10T17:35:00Z';
 assert.equal(ctx.isSeen(),true,'viewed receipt must survive browser restore');
});
test('30 seconds of no activity closes viewer; Player restores private cards before decorative assets',()=>{
 assert.match(player,/const PLAYER_PRIVATE_CARD_IDLE_MS=30000/);
 assert.match(player,/Date\.now\(\)-privateCardActivityAt>=PLAYER_PRIVATE_CARD_IDLE_MS\)closePrivateCardViewer\(\)/);
 assert.match(player,/if\(\$\('#game'\)\?\.dataset\.privateCardView!=='open'\)return/);
 assert.match(player,/document\.addEventListener\('visibilitychange',\(\)=>\{if\(document\.hidden\)closePrivateCardViewer\(\)/);
 assert.match(player,/void loadAvatars\(\)\.catch\(\(\)=>\{\}\);await restore\(\)/);
 assert.match(player,/const resumed=await autoResumeActiveRoom\(\{stayInVillage:false\}\);if\(!resumed\)await enterVillage\(\)/);
});
